/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_algolab_free: (a: number, b: number) => void;
export const __wbg_algoresult_free: (a: number, b: number) => void;
export const algolab_generate_maze_backtracker: (a: number) => void;
export const algolab_generate_maze_prims: (a: number) => void;
export const algolab_new: (a: number, b: number) => number;
export const algolab_render_buffer_len: (a: number) => number;
export const algolab_render_buffer_ptr: (a: number) => number;
export const algolab_reset_all: (a: number) => void;
export const algolab_reset_search: (a: number) => void;
export const algolab_run_astar: (a: number) => number;
export const algolab_run_bfs: (a: number) => number;
export const algolab_run_dfs: (a: number) => number;
export const algolab_run_dijkstra: (a: number) => number;
export const algolab_set_end: (a: number, b: number) => void;
export const algolab_set_start: (a: number, b: number) => void;
export const algolab_set_terrain: (a: number, b: number, c: number) => void;
export const algolab_set_wall: (a: number, b: number, c: number) => void;
export const algoresult_execution_ms: (a: number) => number;
export const algoresult_nodes_explored: (a: number) => number;
export const algoresult_path_found: (a: number) => number;
export const algoresult_path_length: (a: number) => number;
export const __wbg_get_grid_height: (a: number) => number;
export const __wbg_get_grid_width: (a: number) => number;
export const __wbg_grid_free: (a: number, b: number) => void;
export const __wbg_set_grid_height: (a: number, b: number) => void;
export const __wbg_set_grid_width: (a: number, b: number) => void;
export const grid_flush_render_buffer: (a: number) => void;
export const grid_new: (a: number, b: number) => number;
export const grid_render_buffer_len: (a: number) => number;
export const grid_render_buffer_ptr: (a: number) => number;
export const grid_reset_all: (a: number) => void;
export const grid_reset_search_state: (a: number) => void;
export const grid_set_end: (a: number, b: number) => void;
export const grid_set_start: (a: number, b: number) => void;
export const grid_set_terrain: (a: number, b: number, c: number) => void;
export const grid_set_wall: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
